### ISSUE TITLE
npm run test failed

### ISSUE THREAD

**Issue by nfer** [taufique71/node-c-lexer#3]
1) Tests for preprocessor removal unit Should successfully remove preprocessor from case_4.c file:
     Uncaught AssertionError: expected 7 to equal 1
      at test/cpp_unit/cpp_unit.js:113:24
      at node_modules/async/lib/async.js:726:13
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at node_modules/async/lib/async.js:723:17
      at node_modules/async/lib/async.js:167:37
      at test/cpp_unit/cpp_unit.js:106:26
      at lib/cpp-unit.js:87:21
      at ChildProcess.exithandler (child_process.js:265:7)
      at maybeClose (internal/child_process.js:936:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

I add console.log on test/cpp_unit/cpp_unit.js:112
`console.log(results);`
then, the output is below:

```
[ '\n\n\nint main()\n{\n    int i;\n    clock_t time1, time2;\n    time1= clock();\n    for (i=1; i<=100000; i++);\n    time2=clock();\n    printf("%f seconds\\n",(float)(time2-time1)/((clock_t) 1000000));\n\n}\n',
  '\n\n\nint main()\n{\n    int i;\n    clock_t time1, time2;\n    time1= clock();\n    for (i=1; i<=100000; i++);\n    time2=clock();\n    printf("%f seconds\\n",(float)(time2-time1)/1000000l);\n\n}\n' ]
```

OS: Ubuntu 14.04
node: v9.8.0
gcc version 4.8.4

**Comment by taufique71** [comment]
I am on run for a few days. Would take a look within a couple of days and get back to you. If you can find any bug then feel free to fix it and send a pull request.
